### ISSUE TITLE
Component error: dynalite - cannot import name 'BRIDGE_CONFIG_SCHEMA' from 'dynalite_devices_lib'

### ISSUE THREAD

**Issue by lethallynx** [ziv1234/hass_dynalite_component#1]
Trying to get this component working on a fresh install of HassOS on a Raspberry PI 3 B+ 

![image](https://user-images.githubusercontent.com/963869/71317371-57e7ee00-24cb-11ea-9f5a-1346172d9355.png)

**Comment by lethallynx** [comment]
Figured out that if I modify the manifest.json requirments line to:
`"requirements": ["dynalite_devices==0.1.10"]`
Then is fixes the issue.

**Comment by ziv1234** [comment]
thanks

**Comment by ziv1234** [comment]
uploaded the fix. Thanks for catching

**Comment by uzelac** [comment]
similar issue, get an error:
Component error: dynalite - cannot import name 'CONF_CHANNEL' from 'dynalite_lib' (/usr/local/lib/python3.7/site-packages/dynalite_lib/__init__.py)

**Comment by ziv1234** [comment]
This is strange. Are you using the latest version from GitHub? Can you send me your manifest file? Should use dynalite-device 0.1.12, although this constant has been there since the first version, so I might have done something bad that doesn’t happen in my setup.

Also if you can do “pip3 show dynalite” and “pip3 show dynalite-devices” and send me the results, I can confirm it is the right versions and locations

Lastly, if you run “hass –script check_config” to see if something is broken there?

**Comment by uzelac** [comment]
Not that good at Linux, i have Ubuntu in Windows Hyper-V and it worked perfectly until now.
As far as i understand, do i need to have some dynalite libraries at python installed ?
Everything was working perfect with Troy's component, after I transfer config to new component i get this error on check of configuration, HA wont even restart because it recognieses error.

**Comment by ziv1234** [comment]
I am also using it with Ububtu in Windows Hyper-V. How is Home Assistant installed? Is it as hassio? Do you remember how you installed it?

Home Assistant is supposed to install the libraries automatically and it does so on my system, but for some reason it may not be installing the right ones for you so I want to try and understand why.

**Comment by ziv1234** [comment]
BTW, is Troy Kelly’s component still installed? They may be using different versions of this library which could cause this conflict.

**Comment by uzelac** [comment]
I deleted Troy's component since it asks same folder in custom components.
Maybe i should give it some time, remove Troys, restart, stuff like that. Will give it a try.
It is odd for me to see that dynalite folder changes, i insert yor files (DL from github) which are different thay Troys. Troy component has three files in root and extra folder, your component has 10+ files in root.
When i restart, some files change/show up. Haven't compared in detail, but something does change.
Not that much in ubuntu and python to know if that is normal.

In regard to Python and Dynalite, do you know which libraries i need in python to install ?
Can i install them on my own ?

Installation is Ubuntu in Hyper-V with Hass.io in docker.
All seems fine, it is updated to last version recently 103.5 if i remember correctly, lots of addons and integrations which all run OK.

I can upload any .yaml or folder structure/files if you need to debug.

Thanks

**Comment by uzelac** [comment]
> 
> This is strange. Are you using the latest version from GitHub? Can you send me your manifest file? Should use dynalite-device 0.1.12, although this constant has been there since the first version, so I might have done something bad that doesn’t happen in my setup. Also if you can do “pip3 show dynalite” and “pip3 show dynalite-devices” and send me the results, I can confirm it is the right versions and locations Lastly, if you run “hass –script check_config” to see if something is broken there? 

Went into ubuntu and tried pip3 commands -> says pip3 not installed ?!
Installed it with apt-get, whole python3
After installation (without any restarts) pip3 show dynalite shows nothing, just shows command promt again when i press enter, Same with dynalite devices.

Went into hass.io web terminal
typed both pip3 same results, just press enter and after second or two it goes to command prompt.

**Comment by uzelac** [comment]
What is manifest file ? :)

**Comment by uzelac** [comment]
Went into Web terminal for my HA.
Pip3 install dynalite did something
pip3 install dynalite-devices also did something

now when i type pip3 show dynalite i get some info. 
What botthers me most is that location is:
/usr/lib/python3.8/...

and error i get is saying python3.7:
Component error: dynalite - cannot import name 'CONF_CHANNEL' from 'dynalite_lib' (/usr/local/lib/python3.7/site-packages/dynalite_lib/__init__.py)

Could that be a problem ?

**Comment by ziv1234** [comment]
How are you installed? Is it in a venv?

On 5 Jan 2020, at 19:36, Saša Uzelac <notifications@github.com> wrote:

﻿

Went into Web terminal for my HA.
Pip3 install dynalite did something
pip3 install dynalite-devices also did something

now when i type pip3 show dynalite i get some info.
What botthers me most is that location is:
/usr/lib/python3.8/...

and error i get is saying python3.7:
Component error: dynalite - cannot import name 'CONF_CHANNEL' from 'dynalite_lib' (/usr/local/lib/python3.7/site-packages/dynalite_lib/init.py)

Could that be a problem ?

**Comment by uzelac** [comment]
venv ? :

**Comment by uzelac** [comment]
win10 / hyper-v / ubuntu / docker

**Comment by ziv1234** [comment]
Let me try it with a Hassio docker installation to see if I can reproduce. Which image did you use?

On 5 Jan 2020, at 17:50, Saša Uzelac <notifications@github.com> wrote:

﻿

I deleted Troy's component since it asks same folder in custom components.
Maybe i should give it some time, remove Troys, restart, stuff like that. Will give it a try.
It is odd for me to see that dynalite folder changes, i insert yor files (DL from github) which are different thay Troys. Troy component has three files in root and extra folder, your component has 10+ files in root.
When i restart, some files change/show up. Haven't compared in detail, but something does change.
Not that much in ubuntu and python to know if that is normal.

In regard to Python and Dynalite, do you know which libraries i need in python to install ?
Can i install them on my own ?

Installation is Ubuntu in Hyper-V with Hass.io in docker.
All seems fine, it is updated to last version recently 103.5 if i remember correctly, lots of addons and integrations which all run OK.

I can upload any .yaml or folder structure/files if you need to debug.

Thanks

**Comment by uzelac** [comment]
It was some time.
I use NUC so i used some nuc image, by some guide.
Will try to reinstall hass, import everything imporatnat and see how it goes.

Thank for your help, will let you know.

**Comment by uzelac** [comment]
I found guide i used:

https://www.smarthomebeginner.com/install-hass-io-on-docker-linux/

Probably will use it again if i'm going to contiue with Windows/HyperV.
Have some issues with HyperV, but far less than VirutalBox i used earlier... ah, nothing is perfect :)

**Comment by ziv1234** [comment]
Ok. I followed the same thing and ran into the same error, so should be able to resolve it. Will update

**Comment by ziv1234** [comment]
Eventually I got the same error, rebooted the host (via the Hass.io tab) and everything works now. I guess that they check the library dependencies only on reboot

**Comment by uzelac** [comment]
Hmm, just reboot and it will work ? :) Will try right away

**Comment by uzelac** [comment]
Yes, reboot when your dynalite component was in custom_components, and now it doesnt show error on check config!
Now, to set it up and see how it works! :D

Thanks!

**Comment by uzelac** [comment]
It does work, indeed :)
Lots of changes from Troy to this component, lots of things need to change but i finaly got dimmable channels. Hope there wont be any major changes, really can not do this again :)

Presets are still not done perfectly, I guess that is work in progress. Should be made as scenes or profiles, definitely not as switches, maybe template but not 4 on/off switches for 4 presets.

Thanks, good work.

**Comment by ziv1234** [comment]
I will be happy to add this if you explain what you would want from the presets. In my configuration they are only used for on/off, but will be happy to implement something better

**Comment by ziv1234** [comment]
I guess home assistant updates its python library dependencies only on reboot. I could look into it a bit more but since the first reboot solves it, will be difficult to track it down as I will need a full reinstall for every test
